### ISSUE TITLE
sense/move hands implementation

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/RobotInterfaceROS#2]
As described in https://github.com/ADVRHumanoids/RobotInterfaceROS/pull/1

**Comment by alaurenzi** [comment]
I believe that CommunicationHandler should advertise a /xbotcore/robot_name/hand/hand_name/state and subscribe to a /xbotcore/robot_name/hand/hand_name/command, similarly to what is done for motors, ft, imu. Then ROS implementation of RobotInterface should publish/subscribe accordingly

**Comment by pepperig** [comment]
done
